### ISSUE TITLE
Execute Requests with no callbackParams (ie email address) don't work

### ISSUE THREAD

**Issue by akashisama** [aodn/aws-wps#106] opened 2017-10-25 01:02 UTC

**Comment by akashisama** [comment] 2017-10-25 01:08
Showstopper because we wouldn't want to put an email address in the online resource monitor requests, but without one we get a 500 status response and the layer is set to "failed"

**Comment by jonescc** [comment] 2017-10-25 01:09
Duplicate of #88

**Closed** 2017-10-25 01:51 UTC
Labels: bug
